py_library(
    name = "visionai_py",
    srcs = [
        "__init__.py",
    ],
    srcs_version = "PY3",
    visibility = [
        "//visionai:__subpackages__",
    ],
    deps = [
        "//visionai/python",
    ],
)
