package(
    default_visibility = ["//cloud/hosted/visionai:__subpackages__"],
)

licenses(["notice"])

exports_files(
    srcs = [
        "generic_object_detection_analyzer.pbtxt",
        "occupancy_counting_analyzer.pbtxt",
        "person_blur_analyzer.pbtxt",
        "person_vehicle_detection_analyzer.pbtxt",
        "toy_example.pbtxt",
    ],
)
