# Copyright (c) 2023 Google LLC All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

package(
    default_visibility = ["//visionai:__subpackages__"],
    licenses = ["notice"],
)

py_library(
    name = "python",
    srcs = [
        "__init__.py",
    ],
    srcs_version = "PY3",
    deps = [
        "//visionai/python/lva",
        "//visionai/python/net",
        "//visionai/python/ops",
        "//visionai/python/prediction",
        "//visionai/python/protos/googleapis/v1",
        "//visionai/python/recipes",
    ],
)
