package(default_visibility = ["//visionai:__subpackages__"])

licenses(["notice"])

cc_library(
    name = "status_matchers",
    srcs = ["status_matchers.cc"],
    hdrs = ["status_matchers.h"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest",
    ],
)
