# Copyright (c) 2023 Google LLC All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from visionai.python.protos.googleapis.v1 import lva_resources_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2
from visionai.python.protos.googleapis.v1 import lva_service_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2


class LiveVideoAnalyticsStub(object):
    """Service describing handlers for resources. The service enables clients to run
    Live Video Analytics (LVA) on the streaming inputs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAnalyses = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/ListAnalyses',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesResponse.FromString,
                )
        self.GetAnalysis = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/GetAnalysis',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetAnalysisRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Analysis.FromString,
                )
        self.CreateAnalysis = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/CreateAnalysis',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateAnalysisRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateAnalysis = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/UpdateAnalysis',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateAnalysisRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteAnalysis = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/DeleteAnalysis',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteAnalysisRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListProcesses = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/ListProcesses',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesResponse.FromString,
                )
        self.GetProcess = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/GetProcess',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetProcessRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Process.FromString,
                )
        self.CreateProcess = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/CreateProcess',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateProcessRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateProcess = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/UpdateProcess',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateProcessRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteProcess = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/DeleteProcess',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteProcessRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.BatchRunProcess = channel.unary_unary(
                '/google.cloud.visionai.v1.LiveVideoAnalytics/BatchRunProcess',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.BatchRunProcessRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )


class LiveVideoAnalyticsServicer(object):
    """Service describing handlers for resources. The service enables clients to run
    Live Video Analytics (LVA) on the streaming inputs.
    """

    def ListAnalyses(self, request, context):
        """Lists Analyses in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysis(self, request, context):
        """Gets details of a single Analysis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAnalysis(self, request, context):
        """Creates a new Analysis in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAnalysis(self, request, context):
        """Updates the parameters of a single Analysis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAnalysis(self, request, context):
        """Deletes a single Analysis.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcesses(self, request, context):
        """Lists Processes in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcess(self, request, context):
        """Gets details of a single Process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcess(self, request, context):
        """Creates a new Process in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProcess(self, request, context):
        """Updates the parameters of a single Process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProcess(self, request, context):
        """Deletes a single Process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRunProcess(self, request, context):
        """Run all of the processes to "completion". Max time for each process is
        the LRO time limit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiveVideoAnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAnalyses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAnalyses,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesResponse.SerializeToString,
            ),
            'GetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysis,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetAnalysisRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Analysis.SerializeToString,
            ),
            'CreateAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnalysis,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateAnalysisRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAnalysis,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateAnalysisRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAnalysis,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteAnalysisRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcesses,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesResponse.SerializeToString,
            ),
            'GetProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcess,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetProcessRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Process.SerializeToString,
            ),
            'CreateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcess,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateProcessRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProcess,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateProcessRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProcess,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteProcessRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'BatchRunProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRunProcess,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.BatchRunProcessRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.visionai.v1.LiveVideoAnalytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LiveVideoAnalytics(object):
    """Service describing handlers for resources. The service enables clients to run
    Live Video Analytics (LVA) on the streaming inputs.
    """

    @staticmethod
    def ListAnalyses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/ListAnalyses',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListAnalysesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/GetAnalysis',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetAnalysisRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Analysis.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/CreateAnalysis',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateAnalysisRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/UpdateAnalysis',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateAnalysisRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/DeleteAnalysis',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteAnalysisRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/ListProcesses',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.ListProcessesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/GetProcess',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.GetProcessRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__resources__pb2.Process.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/CreateProcess',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.CreateProcessRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/UpdateProcess',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.UpdateProcessRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/DeleteProcess',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.DeleteProcessRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchRunProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.LiveVideoAnalytics/BatchRunProcess',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_lva__service__pb2.BatchRunProcessRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
