# Copyright (c) 2023 Google LLC All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from visionai.python.protos.googleapis.v1 import platform_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2


class AppPlatformStub(object):
    """Service describing handlers for resources
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListApplications = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/ListApplications',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsResponse.FromString,
                )
        self.GetApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/GetApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Application.FromString,
                )
        self.CreateApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/CreateApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UpdateApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/DeleteApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeployApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/DeployApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeployApplicationRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UndeployApplication = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UndeployApplication',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UndeployApplicationRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.AddApplicationStreamInput = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/AddApplicationStreamInput',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.AddApplicationStreamInputRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.RemoveApplicationStreamInput = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/RemoveApplicationStreamInput',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.RemoveApplicationStreamInputRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateApplicationStreamInput = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UpdateApplicationStreamInput',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationStreamInputRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListInstances = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/ListInstances',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesResponse.FromString,
                )
        self.GetInstance = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/GetInstance',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetInstanceRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Instance.FromString,
                )
        self.CreateApplicationInstances = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/CreateApplicationInstances',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationInstancesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteApplicationInstances = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/DeleteApplicationInstances',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationInstancesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateApplicationInstances = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UpdateApplicationInstances',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationInstancesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListDrafts = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/ListDrafts',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsResponse.FromString,
                )
        self.GetDraft = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/GetDraft',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetDraftRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Draft.FromString,
                )
        self.CreateDraft = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/CreateDraft',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateDraftRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateDraft = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UpdateDraft',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateDraftRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteDraft = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/DeleteDraft',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteDraftRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListProcessors = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/ListProcessors',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsResponse.FromString,
                )
        self.ListPrebuiltProcessors = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/ListPrebuiltProcessors',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsResponse.FromString,
                )
        self.GetProcessor = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/GetProcessor',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetProcessorRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Processor.FromString,
                )
        self.CreateProcessor = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/CreateProcessor',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateProcessorRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateProcessor = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/UpdateProcessor',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateProcessorRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteProcessor = channel.unary_unary(
                '/google.cloud.visionai.v1.AppPlatform/DeleteProcessor',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteProcessorRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )


class AppPlatformServicer(object):
    """Service describing handlers for resources
    """

    def ListApplications(self, request, context):
        """Lists Applications in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplication(self, request, context):
        """Gets details of a single Application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApplication(self, request, context):
        """Creates a new Application in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplication(self, request, context):
        """Updates the parameters of a single Application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApplication(self, request, context):
        """Deletes a single Application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployApplication(self, request, context):
        """Deploys a single Application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeployApplication(self, request, context):
        """Undeploys a single Application.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddApplicationStreamInput(self, request, context):
        """Adds target stream input to the Application.
        If the Application is deployed, the corresponding new Application instance
        will be created. If the stream has already been in the Application, the RPC
        will fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveApplicationStreamInput(self, request, context):
        """Remove target stream input to the Application, if the Application is
        deployed, the corresponding instance based will be deleted. If the stream
        is not in the Application, the RPC will fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplicationStreamInput(self, request, context):
        """Update target stream input to the Application, if the Application is
        deployed, the corresponding instance based will be deployed. For
        CreateOrUpdate behavior, set allow_missing to true.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstances(self, request, context):
        """Lists Instances in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Gets details of a single Instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApplicationInstances(self, request, context):
        """Adds target stream input to the Application.
        If the Application is deployed, the corresponding new Application instance
        will be created. If the stream has already been in the Application, the RPC
        will fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteApplicationInstances(self, request, context):
        """Remove target stream input to the Application, if the Application is
        deployed, the corresponding instance based will be deleted. If the stream
        is not in the Application, the RPC will fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateApplicationInstances(self, request, context):
        """Adds target stream input to the Application.
        If the Application is deployed, the corresponding new Application instance
        will be created. If the stream has already been in the Application, the RPC
        will fail.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDrafts(self, request, context):
        """Lists Drafts in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDraft(self, request, context):
        """Gets details of a single Draft.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDraft(self, request, context):
        """Creates a new Draft in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDraft(self, request, context):
        """Updates the parameters of a single Draft.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDraft(self, request, context):
        """Deletes a single Draft.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcessors(self, request, context):
        """Lists Processors in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrebuiltProcessors(self, request, context):
        """ListPrebuiltProcessors is a custom pass-through verb that Lists Prebuilt
        Processors.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessor(self, request, context):
        """Gets details of a single Processor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcessor(self, request, context):
        """Creates a new Processor in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProcessor(self, request, context):
        """Updates the parameters of a single Processor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProcessor(self, request, context):
        """Deletes a single Processor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppPlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetApplicationRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Application.SerializeToString,
            ),
            'CreateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeployApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeployApplicationRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UndeployApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeployApplication,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UndeployApplicationRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'AddApplicationStreamInput': grpc.unary_unary_rpc_method_handler(
                    servicer.AddApplicationStreamInput,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.AddApplicationStreamInputRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'RemoveApplicationStreamInput': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveApplicationStreamInput,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.RemoveApplicationStreamInputRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateApplicationStreamInput': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplicationStreamInput,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationStreamInputRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstances,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesResponse.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetInstanceRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Instance.SerializeToString,
            ),
            'CreateApplicationInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplicationInstances,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationInstancesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteApplicationInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApplicationInstances,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationInstancesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateApplicationInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateApplicationInstances,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationInstancesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListDrafts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDrafts,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsResponse.SerializeToString,
            ),
            'GetDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDraft,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetDraftRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Draft.SerializeToString,
            ),
            'CreateDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDraft,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateDraftRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDraft,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateDraftRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDraft,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteDraftRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListProcessors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcessors,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsResponse.SerializeToString,
            ),
            'ListPrebuiltProcessors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrebuiltProcessors,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsResponse.SerializeToString,
            ),
            'GetProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessor,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetProcessorRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Processor.SerializeToString,
            ),
            'CreateProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcessor,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateProcessorRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProcessor,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateProcessorRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteProcessor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProcessor,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteProcessorRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.visionai.v1.AppPlatform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppPlatform(object):
    """Service describing handlers for resources
    """

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/ListApplications',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListApplicationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/GetApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetApplicationRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Application.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/CreateApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UpdateApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/DeleteApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeployApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/DeployApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeployApplicationRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UndeployApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UndeployApplication',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UndeployApplicationRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddApplicationStreamInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/AddApplicationStreamInput',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.AddApplicationStreamInputRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveApplicationStreamInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/RemoveApplicationStreamInput',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.RemoveApplicationStreamInputRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApplicationStreamInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UpdateApplicationStreamInput',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationStreamInputRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/ListInstances',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListInstancesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/GetInstance',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetInstanceRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Instance.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateApplicationInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/CreateApplicationInstances',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateApplicationInstancesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteApplicationInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/DeleteApplicationInstances',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteApplicationInstancesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateApplicationInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UpdateApplicationInstances',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateApplicationInstancesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDrafts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/ListDrafts',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListDraftsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/GetDraft',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetDraftRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Draft.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/CreateDraft',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateDraftRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UpdateDraft',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateDraftRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/DeleteDraft',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteDraftRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProcessors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/ListProcessors',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListProcessorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPrebuiltProcessors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/ListPrebuiltProcessors',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.ListPrebuiltProcessorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/GetProcessor',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.GetProcessorRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.Processor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/CreateProcessor',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.CreateProcessorRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/UpdateProcessor',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.UpdateProcessorRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProcessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.AppPlatform/DeleteProcessor',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_platform__pb2.DeleteProcessorRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
