# Copyright (c) 2023 Google LLC All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from visionai.python.protos.googleapis.v1 import common_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_common__pb2
from visionai.python.protos.googleapis.v1 import streams_resources_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2
from visionai.python.protos.googleapis.v1 import streams_service_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2


class StreamsServiceStub(object):
    """Service describing handlers for resources.
    Vision API and Vision AI API are two independent APIs developed by the same
    team. Vision API is for people to annotate their image while Vision AI is an
    e2e solution for customer to build their own computer vision application.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListClusters = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/ListClusters',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersResponse.FromString,
                )
        self.GetCluster = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GetCluster',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetClusterRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_common__pb2.Cluster.FromString,
                )
        self.CreateCluster = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/CreateCluster',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateClusterRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateCluster = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/UpdateCluster',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateClusterRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteCluster = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/DeleteCluster',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteClusterRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListStreams = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/ListStreams',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsResponse.FromString,
                )
        self.GetStream = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GetStream',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Stream.FromString,
                )
        self.CreateStream = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/CreateStream',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateStreamRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateStream = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/UpdateStream',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateStreamRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteStream = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/DeleteStream',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteStreamRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GetStreamThumbnail = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GetStreamThumbnail',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamThumbnailRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GenerateStreamHlsToken = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GenerateStreamHlsToken',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenResponse.FromString,
                )
        self.ListEvents = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/ListEvents',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsResponse.FromString,
                )
        self.GetEvent = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GetEvent',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetEventRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Event.FromString,
                )
        self.CreateEvent = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/CreateEvent',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateEvent = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/UpdateEvent',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateEventRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteEvent = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/DeleteEvent',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteEventRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListSeries = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/ListSeries',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesResponse.FromString,
                )
        self.GetSeries = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/GetSeries',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetSeriesRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Series.FromString,
                )
        self.CreateSeries = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/CreateSeries',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateSeriesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateSeries = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/UpdateSeries',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateSeriesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteSeries = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/DeleteSeries',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteSeriesRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.MaterializeChannel = channel.unary_unary(
                '/google.cloud.visionai.v1.StreamsService/MaterializeChannel',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.MaterializeChannelRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )


class StreamsServiceServicer(object):
    """Service describing handlers for resources.
    Vision API and Vision AI API are two independent APIs developed by the same
    team. Vision API is for people to annotate their image while Vision AI is an
    e2e solution for customer to build their own computer vision application.
    """

    def ListClusters(self, request, context):
        """Lists Clusters in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCluster(self, request, context):
        """Gets details of a single Cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCluster(self, request, context):
        """Creates a new Cluster in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCluster(self, request, context):
        """Updates the parameters of a single Cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCluster(self, request, context):
        """Deletes a single Cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStreams(self, request, context):
        """Lists Streams in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """Gets details of a single Stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStream(self, request, context):
        """Creates a new Stream in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStream(self, request, context):
        """Updates the parameters of a single Stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStream(self, request, context):
        """Deletes a single Stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamThumbnail(self, request, context):
        """Gets the thumbnail (image snapshot) of a single Stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStreamHlsToken(self, request, context):
        """Generate the JWT auth token required to get the stream HLS contents.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Lists Events in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvent(self, request, context):
        """Gets details of a single Event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEvent(self, request, context):
        """Creates a new Event in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEvent(self, request, context):
        """Updates the parameters of a single Event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEvent(self, request, context):
        """Deletes a single Event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSeries(self, request, context):
        """Lists Series in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeries(self, request, context):
        """Gets details of a single Series.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSeries(self, request, context):
        """Creates a new Series in a given project and location.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSeries(self, request, context):
        """Updates the parameters of a single Event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSeries(self, request, context):
        """Deletes a single Series.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaterializeChannel(self, request, context):
        """Materialize a channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClusters,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersResponse.SerializeToString,
            ),
            'GetCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCluster,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetClusterRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_common__pb2.Cluster.SerializeToString,
            ),
            'CreateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCluster,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateClusterRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCluster,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateClusterRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCluster,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteClusterRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListStreams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStreams,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsResponse.SerializeToString,
            ),
            'GetStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Stream.SerializeToString,
            ),
            'CreateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStream,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateStreamRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStream,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateStreamRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteStream': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStream,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteStreamRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetStreamThumbnail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamThumbnail,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamThumbnailRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GenerateStreamHlsToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStreamHlsToken,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenResponse.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsResponse.SerializeToString,
            ),
            'GetEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvent,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetEventRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Event.SerializeToString,
            ),
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateEventRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEvent,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateEventRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEvent,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteEventRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSeries,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesResponse.SerializeToString,
            ),
            'GetSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeries,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetSeriesRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Series.SerializeToString,
            ),
            'CreateSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeries,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateSeriesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSeries,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateSeriesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteSeries': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSeries,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteSeriesRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'MaterializeChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.MaterializeChannel,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.MaterializeChannelRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.visionai.v1.StreamsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamsService(object):
    """Service describing handlers for resources.
    Vision API and Vision AI API are two independent APIs developed by the same
    team. Vision API is for people to annotate their image while Vision AI is an
    e2e solution for customer to build their own computer vision application.
    """

    @staticmethod
    def ListClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/ListClusters',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListClustersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GetCluster',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetClusterRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_common__pb2.Cluster.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/CreateCluster',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateClusterRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/UpdateCluster',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateClusterRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/DeleteCluster',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteClusterRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListStreams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/ListStreams',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListStreamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GetStream',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Stream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/CreateStream',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateStreamRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/UpdateStream',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateStreamRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/DeleteStream',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteStreamRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreamThumbnail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GetStreamThumbnail',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetStreamThumbnailRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateStreamHlsToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GenerateStreamHlsToken',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GenerateStreamHlsTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/ListEvents',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GetEvent',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetEventRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Event.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/CreateEvent',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateEventRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/UpdateEvent',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateEventRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/DeleteEvent',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteEventRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/ListSeries',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.ListSeriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/GetSeries',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.GetSeriesRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__resources__pb2.Series.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/CreateSeries',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.CreateSeriesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/UpdateSeries',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.UpdateSeriesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSeries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/DeleteSeries',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.DeleteSeriesRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MaterializeChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.StreamsService/MaterializeChannel',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_streams__service__pb2.MaterializeChannelRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
