# Copyright (c) 2023 Google LLC All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from visionai.python.protos.googleapis.v1 import warehouse_pb2 as visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2


class WarehouseStub(object):
    """Service that manages media content + metadata for streaming.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAsset = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/CreateAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAssetRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
                )
        self.UpdateAsset = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/UpdateAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAssetRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
                )
        self.GetAsset = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GetAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAssetRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
                )
        self.ListAssets = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ListAssets',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsResponse.FromString,
                )
        self.DeleteAsset = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/DeleteAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAssetRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.CreateCorpus = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/CreateCorpus',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateCorpusRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GetCorpus = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GetCorpus',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetCorpusRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.FromString,
                )
        self.UpdateCorpus = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/UpdateCorpus',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateCorpusRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.FromString,
                )
        self.ListCorpora = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ListCorpora',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaResponse.FromString,
                )
        self.DeleteCorpus = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/DeleteCorpus',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteCorpusRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CreateDataSchema = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/CreateDataSchema',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateDataSchemaRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
                )
        self.UpdateDataSchema = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/UpdateDataSchema',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateDataSchemaRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
                )
        self.GetDataSchema = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GetDataSchema',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetDataSchemaRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
                )
        self.DeleteDataSchema = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/DeleteDataSchema',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteDataSchemaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListDataSchemas = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ListDataSchemas',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasResponse.FromString,
                )
        self.CreateAnnotation = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/CreateAnnotation',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAnnotationRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
                )
        self.GetAnnotation = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GetAnnotation',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAnnotationRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
                )
        self.ListAnnotations = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ListAnnotations',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsResponse.FromString,
                )
        self.UpdateAnnotation = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/UpdateAnnotation',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAnnotationRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
                )
        self.DeleteAnnotation = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/DeleteAnnotation',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAnnotationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.IngestAsset = channel.stream_stream(
                '/google.cloud.visionai.v1.Warehouse/IngestAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetResponse.FromString,
                )
        self.ClipAsset = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ClipAsset',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetResponse.FromString,
                )
        self.GenerateHlsUri = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GenerateHlsUri',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriResponse.FromString,
                )
        self.CreateSearchConfig = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/CreateSearchConfig',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateSearchConfigRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
                )
        self.UpdateSearchConfig = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/UpdateSearchConfig',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateSearchConfigRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
                )
        self.GetSearchConfig = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/GetSearchConfig',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetSearchConfigRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
                )
        self.DeleteSearchConfig = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/DeleteSearchConfig',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteSearchConfigRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListSearchConfigs = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/ListSearchConfigs',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsResponse.FromString,
                )
        self.SearchAssets = channel.unary_unary(
                '/google.cloud.visionai.v1.Warehouse/SearchAssets',
                request_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsRequest.SerializeToString,
                response_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsResponse.FromString,
                )


class WarehouseServicer(object):
    """Service that manages media content + metadata for streaming.
    """

    def CreateAsset(self, request, context):
        """Creates an asset inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAsset(self, request, context):
        """Updates an asset inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAsset(self, request, context):
        """Reads an asset inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAssets(self, request, context):
        """Lists an list of assets inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAsset(self, request, context):
        """Deletes asset inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCorpus(self, request, context):
        """Creates a corpus inside a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCorpus(self, request, context):
        """Gets corpus details inside a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCorpus(self, request, context):
        """Updates a corpus in a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCorpora(self, request, context):
        """Lists all corpora in a project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCorpus(self, request, context):
        """Deletes a corpus only if its empty.
        Returns empty response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDataSchema(self, request, context):
        """Creates data schema inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataSchema(self, request, context):
        """Updates data schema inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataSchema(self, request, context):
        """Gets data schema inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataSchema(self, request, context):
        """Deletes data schema inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataSchemas(self, request, context):
        """Lists a list of data schemas inside corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAnnotation(self, request, context):
        """Creates annotation inside asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnnotation(self, request, context):
        """Reads annotation inside asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAnnotations(self, request, context):
        """Lists a list of annotations inside asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAnnotation(self, request, context):
        """Updates annotation inside asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAnnotation(self, request, context):
        """Deletes annotation inside asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestAsset(self, request_iterator, context):
        """Ingests data for the asset. It is not allowed to ingest a data chunk which
        is already expired according to TTL.
        This method is only available via the gRPC API (not HTTP since
        bi-directional streaming is not supported via HTTP).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClipAsset(self, request, context):
        """Generates clips for downloading. The api takes in a time range, and
        generates a clip of the first content available after start_time and
        before end_time, which may overflow beyond these bounds.
        Returned clips are truncated if the total size of the clips are larger
        than 100MB.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateHlsUri(self, request, context):
        """Generates a uri for an HLS manifest. The api takes in a collection of time
        ranges, and generates a URI for an HLS manifest that covers all the
        requested time ranges.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSearchConfig(self, request, context):
        """Creates a search configuration inside a corpus.

        Please follow the rules below to create a valid CreateSearchConfigRequest.
        --- General Rules ---
        1. Request.search_config_id must not be associated with an existing
        SearchConfig.
        2. Request must contain at least one non-empty search_criteria_property or
        facet_property.
        3. mapped_fields must not be empty, and must map to existing UGA keys.
        4. All mapped_fields must be of the same type.
        5. All mapped_fields must share the same granularity.
        6. All mapped_fields must share the same semantic SearchConfig match
        options.
        For property-specific rules, please reference the comments for
        FacetProperty and SearchCriteriaProperty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSearchConfig(self, request, context):
        """Updates a search configuration inside a corpus.

        Please follow the rules below to create a valid UpdateSearchConfigRequest.
        --- General Rules ---
        1. Request.search_configuration.name must already exist.
        2. Request must contain at least one non-empty search_criteria_property or
        facet_property.
        3. mapped_fields must not be empty, and must map to existing UGA keys.
        4. All mapped_fields must be of the same type.
        5. All mapped_fields must share the same granularity.
        6. All mapped_fields must share the same semantic SearchConfig match
        options.
        For property-specific rules, please reference the comments for
        FacetProperty and SearchCriteriaProperty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSearchConfig(self, request, context):
        """Gets a search configuration inside a corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSearchConfig(self, request, context):
        """Deletes a search configuration inside a corpus.

        For a DeleteSearchConfigRequest to be valid,
        Request.search_configuration.name must already exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSearchConfigs(self, request, context):
        """Lists all search configurations inside a corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchAssets(self, request, context):
        """Search media asset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAssetRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.SerializeToString,
            ),
            'UpdateAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAssetRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.SerializeToString,
            ),
            'GetAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAssetRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.SerializeToString,
            ),
            'ListAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAssets,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsResponse.SerializeToString,
            ),
            'DeleteAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAssetRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'CreateCorpus': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCorpus,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateCorpusRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetCorpus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCorpus,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetCorpusRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.SerializeToString,
            ),
            'UpdateCorpus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCorpus,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateCorpusRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.SerializeToString,
            ),
            'ListCorpora': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCorpora,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaResponse.SerializeToString,
            ),
            'DeleteCorpus': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCorpus,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteCorpusRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateDataSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataSchema,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateDataSchemaRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.SerializeToString,
            ),
            'UpdateDataSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataSchema,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateDataSchemaRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.SerializeToString,
            ),
            'GetDataSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataSchema,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetDataSchemaRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.SerializeToString,
            ),
            'DeleteDataSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataSchema,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteDataSchemaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListDataSchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataSchemas,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasResponse.SerializeToString,
            ),
            'CreateAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAnnotation,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAnnotationRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.SerializeToString,
            ),
            'GetAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnnotation,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAnnotationRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.SerializeToString,
            ),
            'ListAnnotations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAnnotations,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsResponse.SerializeToString,
            ),
            'UpdateAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAnnotation,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAnnotationRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.SerializeToString,
            ),
            'DeleteAnnotation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAnnotation,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAnnotationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'IngestAsset': grpc.stream_stream_rpc_method_handler(
                    servicer.IngestAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetResponse.SerializeToString,
            ),
            'ClipAsset': grpc.unary_unary_rpc_method_handler(
                    servicer.ClipAsset,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetResponse.SerializeToString,
            ),
            'GenerateHlsUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateHlsUri,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriResponse.SerializeToString,
            ),
            'CreateSearchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSearchConfig,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateSearchConfigRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.SerializeToString,
            ),
            'UpdateSearchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSearchConfig,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateSearchConfigRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.SerializeToString,
            ),
            'GetSearchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSearchConfig,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetSearchConfigRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.SerializeToString,
            ),
            'DeleteSearchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSearchConfig,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteSearchConfigRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListSearchConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSearchConfigs,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsResponse.SerializeToString,
            ),
            'SearchAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchAssets,
                    request_deserializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsRequest.FromString,
                    response_serializer=visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.visionai.v1.Warehouse', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Warehouse(object):
    """Service that manages media content + metadata for streaming.
    """

    @staticmethod
    def CreateAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/CreateAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAssetRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/UpdateAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAssetRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GetAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAssetRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Asset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ListAssets',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/DeleteAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAssetRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCorpus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/CreateCorpus',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateCorpusRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCorpus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GetCorpus',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetCorpusRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCorpus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/UpdateCorpus',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateCorpusRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Corpus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCorpora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ListCorpora',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListCorporaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCorpus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/DeleteCorpus',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteCorpusRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateDataSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/CreateDataSchema',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateDataSchemaRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDataSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/UpdateDataSchema',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateDataSchemaRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GetDataSchema',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetDataSchemaRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DataSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDataSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/DeleteDataSchema',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteDataSchemaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDataSchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ListDataSchemas',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListDataSchemasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/CreateAnnotation',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateAnnotationRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GetAnnotation',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetAnnotationRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAnnotations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ListAnnotations',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListAnnotationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/UpdateAnnotation',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateAnnotationRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.Annotation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAnnotation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/DeleteAnnotation',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteAnnotationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IngestAsset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/google.cloud.visionai.v1.Warehouse/IngestAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.IngestAssetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClipAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ClipAsset',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ClipAssetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateHlsUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GenerateHlsUri',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GenerateHlsUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSearchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/CreateSearchConfig',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.CreateSearchConfigRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSearchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/UpdateSearchConfig',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.UpdateSearchConfigRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSearchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/GetSearchConfig',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.GetSearchConfigRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteSearchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/DeleteSearchConfig',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.DeleteSearchConfigRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSearchConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/ListSearchConfigs',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.ListSearchConfigsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.visionai.v1.Warehouse/SearchAssets',
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsRequest.SerializeToString,
            visionai_dot_python_dot_protos_dot_googleapis_dot_v1_dot_warehouse__pb2.SearchAssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
